<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\Util\Util_EFCore_SQLite\Util_EFCore_SQLite.csproj" />
    <ProjectReference Include="..\..\Util\Util_BgJob_Quartz\Util_BgJob_Quartz.csproj" />
    <ProjectReference Include="..\..\Util\Util_IdGen_SnowFlakeId\Util_IdGen_SnowFlakeId.csproj" />
    <ProjectReference Include="..\..\Util\Util_Log_Serilog\Util_Log_Serilog.csproj" />
  </ItemGroup>
</Project>